title: "The Japanese Maple Book"
version: "2.1"
description: "A comprehensive guide to Japanese Maples."
url: "https://rightedges.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/japanese-maple-book" # the subpath of your site, e.g. /blog
google_analytics: "G-W8NK7SYEQR"
theme: just-the-docs

# Enable the detailed sidebar
side_bar_label: "Japanese Maple Book"

# Just-the-Docs Configuration
search_enabled: true
footer_content: "Â© 2025 rightedges with Gemini AI. All rights reserved."
aux_links:
  "GitHub Repository": "https://github.com/rightedges/japanese-maple-book"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  cultivars:
    output: true
    permalink: /cultivars/:path
